object Versions {
    const val coreKtx = "1.9.0"
    const val appcompat = "1.6.1"
    const val material = "1.1.2"
    const val lifecycleRuntimeKtx = "2.6.1"
    const val activityCompose = "1.7.2"
    const val compose = "2023.03.00"
    const val composeUiToolingPreview = "1.5.2"
    const val navigationCompose = "2.7.0"
    const val lifecycleViewModelKtx = "2.6.1"
    const val hiltNavigationCompose = "1.0.0"
    const val retrofit = "2.9.0"
    const val moshi = "1.15.0"
    const val moshiConverter = "2.9.0"
    const val gsonConverter = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val loggingInterceptor = "4.8.1"
    val coroutineCore = "1.7.3"
    const val hilt = "2.48.1"
    const val hiltCompiler = "1.1.0-beta01"
}